### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by berkormanli** [Plazide/node-twitch#8]
`TypeError: Cannot read property 'join' of undefined
    at TwitchApi._getAppAccessToken (C:\Users\khadg\Desktop\zXBot\node_modules\node-twitch\index.js:124:23)
    at new TwitchApi (C:\Users\khadg\Desktop\zXBot\node_modules\node-twitch\index.js:67:9)
    at Object.<anonymous> (C:\Users\khadg\Desktop\zXBot\twitchAPI.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`
I had this error on my console when I tried to get the basic 'Live' information like you did on documentation. Can you help me please?

**Comment by Plazide** [comment]
Hey, @berkormanli 

I am actually almost done rewriting the entire package in Typescript while adding support for more endpoints. I will publish the new version as soon as possible, and that should solve your issue. 

I'll leave a comment in this issue when I have published the new version.

**Comment by Plazide** [comment]
@berkormanli 

A new version of the package has been published. Install `node-twitch@0.2.1` to get the latest.

Let me know if your issue has been resolved.

**Comment by berkormanli** [comment]
Yes, this version resolved my issue. Thanks for updating!
